config/routes.rb
Rails.application.routes.draw do

  # home
  get "/"  => "home#top"

  # posts
  post "posts/create" => "posts#create" 
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"

  # users
  get "signup" => "users#new"
  get "users/create" => "users#create"
  post "users/create" => "users#create"
  get "users/index" => "users#index"
  get "login" => "home#top"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "logout" => "users#logout"

  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # likes
  resources :posts do
  resource :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

    belongs_to :user
    has_many :posts

end

app/models/post.rb
class Post < ApplicationRecord

    validates :item_name, {presence: true}
    validates :price, {presence: true}

    belongs_to :user
    has_many :likes
    has_many :tag_relationships, dependent: :destroy
    has_many :tags, through: :tag_relationships

    def liked_by?(user)
     likes.where(user_id: user.id).exists?
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"

    validates :follower_id, presence: true
    validates :following_id, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_relationships, dependent: :destroy
    has_many :posts, through: :tag_relationships
    validates :name, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, {presence: true}
    validates :password, {presence: true,uniqueness: true}

    has_many :likes
    has_many :posts

    #relationship
    has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
    has_many :followings, through: :following_relationships
    has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
    has_many :followers, through: :follower_relationships

    def following?(other_user)
        self.followings.include?(other_user)
    end
      
    def follow(other_user)
        self.following_relationships.create(following_id: other_user.id)
    end
      
    def unfollow(other_user)
        self.following_relationships.find_by(following_id: other_user.id).destroy
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :null_session
before_action :set_current_user

    def authenticate_user
        if @current_user == nil
        flash[:notice] = "ログインが必要です"
        redirect_to("/login")
        end
    end

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def user
        return User.find_by(id: self.user_id)
    end

    def forbid_login_user
        if @current_user
            flash[:notice] = "すでにログインしています"
            redirect_to("/posts/index")
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user, {only: [:top, :about]}
  
  def top

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        like = @current_user.likes.build(post_id: params[:post_id])
        like.save
    end

    def destroy
        @post = Post.find(params[:post_id])
        like = Like.find_by(post_id: params[:post_id], user_id: @current_user.id)
        like.destroy
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @post = Post.new
    @user = User.all
  end

  def new
    @post = Post.new
  end

  def create
    @posts = Post.all
    @post = @current_user.posts.build(post_params)
    @post.save
    @post.post_imgname = "#{@post.id}_postimage.jpg"
    image = params[:image]
    File.binwrite("public/post_images/#{@post.post_imgname}", image.read)
    if @post.save
      flash[:notice] = "投稿を保存しました"
      redirect_to("/posts/index")
    else
      flash[:notice] = "投稿内容に誤りがあります。"
      render("/posts/new")
    end
  end

  def edit
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html {redirect_back(fallback_location: posts_path)}
      format.js
    end  
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    @post.save
    respond_to do |format|
      format.html {redirect_back(fallback_location: posts_path)}
      format.js
    end  
  end


  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html {redirect_back(fallback_location: posts_path)}
      format.js
    end
  end 

  private
  def post_params #post_paramsの定義（ないとエラーになる）
    params.require(:post).permit(
      :item_name,
      :price,
      :comment,
    )
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
      @user = User.find(params[:relationship][:following_id])#→123などの特定の数字（user.idの部分）
      #form_withで作られたリクエスト情報
      @current_user.follow(@user)
      respond_to do |format|
        format.html {redirect_back(fallback_location: root_path)}
        format.js
      end
    end
    
    def destroy
      @user = User.find(params[:relationship][:following_id])
      @current_user.unfollow(@user)
      respond_to do |format|
          format.html {redirect_back(fallback_location: root_path)}
          format.js
      end
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :set_current_user
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}


  def index
  end

  def login_form
  end

  def logout
    session[:user_id] = nil
    redirect_to("/")
    flash[:notice] = "ログアウトしました"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:email],password: params[:password],name: params[:name])
    if @user.save
      flash[:notice] = "新規登録が完了しました"
      session[:user_id] = @user.id
      redirect_to("/posts/index")
    else
      @email = params[:email]
      @name = params[:name]
      @password = params[:password]
      @error_message = "入力内容に不備があります"
      render("/users/new")
    end
  end

  def login
    @user = User.find_by(email: params[:email],password: params[:password])
    if @user
      flash[:notice] = "ログインしました"
      session[:user_id] = @user.id
      redirect_to("/posts/index")
    else
      flash[:notice] = "メールアドレスか、パスワードに誤りがあります"
      @email = params[:email]
      @password = params[:password]
      render("/home/top")
    end
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(10)
    render "show_followings"
  end
  
  def followers
      @user = User.find(params[:id])
      @users = @user.followers.page(params[:page]).per(10)
      render "show_followers"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class = "top-main">
  <div class="main-about">
    <p>BUYEDはみんなの「買った！」を共有するアプリです</p>
    <p>あなたの今日買ってきたものを、ログインしてシェアしてみましょう！</p>
  </div>

  <div class="main users-login">
    <div class="container">
      <div class="form users-form">
        <div class="form-body">
          <% if @error_message %>
            <div class="form-error">
              <%= @error_message %>
            </div>
          <% end %>
            <%= form_tag("/login") do %>
              <p>メールアドレス</p>
              <input name="email" value="<%= @email %>">
              <p>パスワード</p>
              <input type="password" name="password" value="<%= @password %>">
              <input type="submit" value="ログイン">
            <% end %>
        </div>
              <div class="signup">
              <p>アカウントをお持ちでない場合は… <%= link_to("新規登録","/signup",class:"signup-btn") %>
              </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BUYED</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">

  </head>
  <body>
    <header>
      <div class="header-logo"> 
        <%= link_to("/") do %>
        <img src="/BUYED logo.jpg" class= "logo">
        <% end %>
      </div>
        <ul class="header-menu">
          <% if @current_user %>
            <li>
            <%= @current_user.name %>さん
          <% else %>
          ログインしていません…
            </li>
          <% end %>
            <li>
            <%= link_to("BUYEDについて","/about",class:"li-list") %>
            </li>
            <li>
            <%= link_to("投稿一覧","/posts/index",class:"li-list") %>
            </li>
             <li>
            <%= link_to("投稿する","/posts/new",class:"li-list") %>
            </li>
            <li>
            <%= link_to("ログアウト","/logout",{method: :post, class:"li-list"})  %> 
            </li>
        </ul>
  </header>
      <% if flash[:notice] %>
        <div class="fade-in-flash"><%= flash[:notice] %></div>
      <% end %>
    <%= yield %>
  </body>

</html>

app/views/likes/_like.html.erb
<% if post.liked_by?(@current_user) %>
    <%= link_to post_likes_path(post.id), method: :delete, remote: true do %>
        <i class="far fa-heart unlike-btn fa-2x"><p class="likes_count"><%= post.likes.count %></p></i>
    <% end %>
<% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
        <i class="far fa-heart like-btn fa-2x"><p class="likes_count"><%= post.likes.count %></p></i>
    <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_edit.html.erb
<div id="img-modal<%= post.id %>" class="modal">
    <div class="modal-content">
        <div class="modal-body">
<!--modal left-->
            <div class="modal-left-info">
                <img class="modal-img" src=<%="/post_images/#{post.post_imgname}"%>>
            </div>
<!--modal right-->
            <div class="modal-right-info">
                <div class="left-section">
                    <img class="mo-user-icon" src="/default-user-icon.png">
                    <div class="mo-user-name"><%= post.user.name %></div>
<% if @current_user && post.user != @current_user %>
                    <div id="follow_buttons_<%= post.user.id %>" class="follow-btn">
                        <%= render partial: 'posts/user_follow', locals: {user: post.user} %>
                    </div>
<% end %>
                </div>
<%= form_with model: post do |form| %>
                <div class="right-section"></div>
                <%= form.submit "更新"%>
                <%= form.submit "削除"%>


<!--info-->
                <div class="mo-main-infocontainer-edit">
                    <i class="fa fa-tags"></i></p>
                    <i class="far fa-clock"></i><%= post.created_at =%></p>
                    <i class="fa fa-shopping-bag"></i><%= form.text_field :item_name %></p>
                    <i class="fa fa-money"></i><i class="fa fa-jpy"></i><%= form.text_field :price %></p>
                    <i class="fa fa-star-half-empty"></i></p>
                    <i class="fa fa-pencil-square-o"></i><%= form.text_area :comment %></p>
<% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/_show.html.erb
<div id="img-modal<%= post.id %>" class="modal">
    <div class="modal-content">
        <div class="modal-body">
<!--modal left-->
            <div class="modal-left-info">
                <img class="modal-img" src=<%="/post_images/#{post.post_imgname}"%>>
            </div>
<!--modal right-->
            <div class="modal-right-info">
                <div class="left-section">
                    <img class="mo-user-icon" src="/default-user-icon.png">
                    <div class="mo-user-name"><%= post.user.name %></div>
<% if @current_user && post.user != @current_user %>
                    <div id="follow_buttons_<%= post.user.id %>" class="follow-btn">
                        <%= render partial: 'posts/user_follow', locals: {user: post.user} %>
                    </div>
<% end %>
                </div>
                <div class="right-section">
                    <div class="mo-someicon">
<% if @current_user && post.user == @current_user %>
                        <%= link_to edit_post_path(post.id), remote: true do %>
                            <i class="fas fa-pencil-alt fa-2x" id=""></i>
                        <% end %>
<% end %>
                        <i class="far fa-comment fa-2x"></i>
                        <i id="likes_buttons_<%= post.id %>">
                            <%= render partial: 'likes/like', locals: {post: post} %>
                        </i>
                    </div>
                </div>
<!--info-->
                <div class="mo-main-infocontainer">
                    <p><i class="fa fa-tags"></i></p>
                    <p><i class="far fa-clock"></i><%= post.created_at =%></p>
                    <p><i class="fa fa-shopping-bag"></i><%= post.item_name =%></p>
                    <p><i class="fa fa-money"></i><i class="fa fa-jpy"></i><%= post.price %></p>
                    <p><i class="fa fa-star-half-empty"></i></p>
                    <p><i class="fa fa-pencil-square-o"></i><%= post.comment %></p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/_user_follow.html.erb
<% if @current_user.following?(user) %>
    <%= form_with(model: @current_user.following_relationships.find_by(following_id: user.id), method: :delete) do |f| %>
        <%= f.hidden_field :following_id, value: user.id %>
        <%= f.submit "フォロー中", class: "follow-btn" %>
    <% end %>
<% else %>
    <%= form_with(model: @current_user.following_relationships.build) do |f| %>
        <%= f.hidden_field :following_id, value: user.id %>
        <%= f.submit "フォローする", class: "follow-btn" %>
    <% end %>
<% end %>

app/views/posts/edit.js.erb
$("#modal").hide()
$("#modal").html('<%= j(render :partial => 'posts/edit', locals: { post: @post }) %>');
$("#modal").show()

app/views/posts/index.html.erb
<div class="posts-layout">
   <div class="container">
       <% @posts.each do |post| %>
            <div class="posts-main-container">
                <img class="user-icon" src="/default-user-icon.png">
                <div class="user-name"><%= post.user.name %></div>
                    <div class="img-container" id="img_container_<%= post.id %>">
                        <%= link_to image_tag("/post_images/#{post.post_imgname}" , class: "item-img"), post_path(post.id), remote: true %>
                    </div>
                 </div>
        <% end %>
    </div>
</div>
<div id="modal"></div>
<!--modal script -->
<script>

$(document).on('click', function(e) {
    if (!$(e.target).closest($('.modal-content')).length) {
        console.log("out of modal");
        $('.modal').fadeOut();
    }else{
        console.log("in modal");
    };
});

document.onkeyup = function (e) {
    e = e || window.event;
    if(e.keyCode === 27) $('.modal').fadeOut();
};

</script>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
      <div class="form">
        <div class="form-body">
            <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
            <% end %>
              <%= form_with model: @post , multipart: true do |f| %>
                <p>image</p>
                  <input name="image" type="file">
                <p>item_name</p>
                  <%= f.text_field :item_name %>
                <p>Price</p>
                  <%= f.text_field :price, class: 'price' %>円
                <p>Comment</p>
                  <%= f.text_area :comment %>
                <p>Tag</p>
                  <%= f.text_field :tag_ids, placeholder: "タグを付けましょう！複数つけるには','で区切ってください。" %>
                <input type="submit" value="投稿">
              <% end %>
        </div>
      </div>
  </div>
</div>

app/views/posts/show.js.erb
$("#modal").hide()
$("#modal").html('<%= j(render :partial => 'posts/show', locals: { post: @post }) %>');
$("#modal").fadeIn()

app/views/posts/update.js.erb
$("#modal").hide()
$("#modal").html('<%= j(render :partial => 'posts/show', locals: { post: @post }) %>');
$("#modal").show()

app/views/relationships/create.js.erb
$("#follow_buttons_<%= @user.id %>").html("<%= j(render partial: 'posts/user_follow', locals: { user: @user }) %>");

app/views/relationships/destroy.js.erb
$("#follow_buttons_<%= @user.id %>").html("<%= j(render partial: 'posts/user_follow', locals: { user: @user }) %>");

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/login_form.html.erb
this is login_form

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>

        <%= form_tag("/users/create",method: :post) do %> 
        <p>ニックネーム</p>
        <input name="name" value="<%= @name %>">
        <p>メールアドレス</p>
        <input name="email" value="<%= @email %>">
        <p>パスワード</p>
        <input type="password" name="password" value="<%= @password %>">
        <input type="submit" value="登録">
        <% end %>
      </div>
    </div>    
  </div>
</div>